import Document, { Head, Main, NextScript, Html } from 'next/document';

class MyDocument extends Document {
    static async getInitialProps(ctx) {
      const initialProps = await Document.getInitialProps(ctx);
      const { pathname } = ctx;
      const lang = pathname.startsWith("/pt-BR") ? "pt-BR" : "en-US";
      return { ...initialProps, lang };
    }
  
    render() {
      const { lang } = this.props;
      return (
        <Html lang={lang}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="theme-color" content="#FFFFFF"/>
            <link rel="icon" href="/favicon.ico" />
            <link rel="apple-touch-icon" href="https://cdn.glitch.com/49d34dc6-8fbd-46bb-8221-b99ffd36f1af%2Ftouchicon-180.png?v=1566411949736" />
          </Head>
          <body>
            <Main />
            <NextScript />
          </body>
        </Html>
      );
    }
};

export default MyDocument;